### ISSUE TITLE
Activity G.2.4: Regular (annual/seasonal/monthly) RA statements on water resources

### ISSUE THREAD

**Issue by psaile** [psaile/hcp-poa-hydrology#112]
## Responsibility
Regional Associations

## Contributors
SERCOM, HCP, RCOFs, RCCs

## Partners
Members, FAO, GWP

## Linkages
RCOFs, RCCs, HydroSOS

## Success criteria
Number of RAs producing statements

## Activity Start Date
2023

## Activity End Date
2030

## Milestone(s)

- [ ] 2023: [RA statement concept paper] Validated by Hydrological Advisors-JA
- [ ] 2025: One RA statement produced 
- [ ] 2026: Two RA statements produced 
- [ ] 2027: Three RA statements produced 
- [ ] 2028: Four RA statements produced 
- [ ] 2029: Five RA statements produced 
- [ ] 2030: Six RA statements produced
