### ISSUE TITLE
Activity C.8.1: Development of Global Drought Classification System and guidance on drought indicators, including water scarcity and other hydrological indicators - regional/national/basin indicators to be developed

### ISSUE THREAD

**Issue by psaile** [psaile/hcp-poa-hydrology#138]
## Responsibility
[SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom)

## Partners
[GWP](https://www.gwp.org/), [FAO](https://www.fao.org/)

## Linkages
RCOFs, RCCs, [HydroSOS](https://community.wmo.int/en/activity-areas/global-hydrological-status-and-outlook-system-hydrosos)

## Success criteria
Drought indicators for hydrological drought approved by [SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom)

## Activity End Date
2025

## Milestone(s)
- [ ] 2022: Draft GDCS Concept Note approved by [SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom) and EC
- [ ] 2023: Final GDCS Implementation Plan developed
- [ ] 2024: GDCS IP approved by [SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom)-3 and start to implement plan
- [ ] 2025: Continue to implement plan and focus on hydrological indicators
