### ISSUE TITLE
Activity A.2.5: Management programme motivational speeches (similar to TED Talks)

### ISSUE THREAD

**Issue by psaile** [psaile/hcp-poa-hydrology#14]
Sharing experience through videos in a format similar to TED Talks explaining basic management issues of NHSs and methods to cope with them, etc.

## Responsibility
Secretariat

## Contributors
[HCP](https://community.wmo.int/en/activity-areas/hydrology-and-water-resources/hydrological-coordination-panel), [SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom), [INFCOM](https://community.wmo.int/en/governance/commission-membership/commission-observation-infrastructure-and-information-systems-infcom), [RB](https://community.wmo.int/en/governance/commission-membership/research-board)

## Partners
UN System Staff College, UNOG, [Members](https://wmo.int/about-wmo/wmo-members), NHSs

## Linkages
A.4.2, E.2.3

## Success criteria
6 videos

## Activity End Date
2026

## Milestone(s)
- [ ] 2023: First video and live session presented to HA at Cg-19
- [ ] 2024: TED talks channel available
- [ ] 2025: Live session at HA 2025
- [ ] 2026: 6 TED Talks
