### ISSUE TITLE
Activity A.4.3: Catalogue of case studies of product and service development as well as marketing strategies for customers and development of process/checklist, methodology to support strategic service planning of NMHSs, including catalogues of products and services in response to customer requirements

### ISSUE THREAD

**Issue by psaile** [psaile/hcp-poa-hydrology#18]
Demonstration of good practice in the development of customer/user-oriented products and services

## Responsibility
[SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom)

## Contributors
[INFCOM](https://community.wmo.int/en/governance/commission-membership/commission-observation-infrastructure-and-information-systems-infcom), [HCP](https://community.wmo.int/en/activity-areas/hydrology-and-water-resources/hydrological-coordination-panel)

## Partners
UN System Staff College, UNOG

## Success criteria
Catalogue made available

## Activity End Date
2027

## Milestone(s)
- [ ] 2024: Review of requirements from NHSs on form and content
- [ ] 2025: Electronic version of catalogue initiated
- [ ] 2027: Electronic version of catalogue available
