### ISSUE TITLE
Activity A.10.2: Invitation of private sector partners to meetings and sessions such as Hydrological Assembly, RA Hydrological Forum, RA session, etc. to share knowledge

### ISSUE THREAD

**Issue by psaile** [psaile/hcp-poa-hydrology#28]
Based on cooperation developed under #33 and #107  private sector partners to be invited to meetings and sessions to share knowledge on collaborative activities such as new technological solutions, pilot projects and studies.

## Responsibility
Secretariat

## Contributors
[HCP](https://community.wmo.int/en/activity-areas/hydrology-and-water-resources/hydrological-coordination-panel), Regional Offices, [INFCOM](https://community.wmo.int/en/governance/commission-membership/commission-observation-infrastructure-and-information-systems-infcom), [SERCOM](https://community.wmo.int/en/governance/commission-membership/sercom), [RAs](https://community.wmo.int/en/governance/regional-association)

## Partners
Private sector

## Linkages
#33, #107, SC-HYD M8

## Success criteria
Number of private sector partners participating in meetings and activities

## Activity End Date
2027

## Milestone(s)
- [ ] 2023: Participation of private sector partners in Hydrological Assembly 
- [ ] 2024: Participation of private sector in high-level sessions (UNECE Water Convention MOP 10 and UNCCD COP-16) 
- [ ] 2025: Private sector partners invited to meetings and sessions 
- [ ] 2026: A concept paper outlining goals & constraints for private sector participation is prepared and it includes showcases/recommendations on how the future infrastructure for data processing and earth system forecast should be built with multiple-sector partners
